//! Translation from mufw's `Rule` model to `pfctl` filter rules.
//!
//! NOTE: `pfctl-rs` is deliberately low-level and its API surface shifts
//! between minor versions. The translation here targets the stable subset
//! (action, direction, interface, proto, endpoints, ports, quick). Features
//! like `max-src-conn-rate` used by `Action::Limit` are rendered via the
//! textual anchor path in `anchor.rs` until upstream pfctl-rs gains native
//! support.

use pfctl::{FilterRuleBuilder, Proto as PfProto};

use crate::error::Result;
use crate::rule::{Action, Proto, Rule, Target};

/// Returns `true` when this rule is best expressed directly through the
/// `pfctl` crate. Rate-limit rules round-trip better through the anchor text.
pub fn is_native(rule: &Rule) -> bool {
    !matches!(rule.action, Action::Limit)
}

/// Render a rule as a single pf anchor line (used by the textual path).
pub fn to_anchor_line(rule: &Rule) -> String {
    let mut parts: Vec<String> = Vec::new();
    match rule.action {
        Action::Allow => parts.push("pass in".into()),
        Action::Deny => parts.push("block in quick".into()),
        Action::Limit => parts.push("pass in".into()),
    }
    if let Some(iface) = &rule.interface {
        parts.push(format!("on {iface}"));
    }
    match rule.proto {
        Proto::Tcp => parts.push("proto tcp".into()),
        Proto::Udp => parts.push("proto udp".into()),
        Proto::Any => {
            if rule.port.is_some() {
                // pf requires a proto when using ports; default to tcp.
                parts.push("proto tcp".into());
            }
        }
    }
    parts.push(format!("from {}", target_or_any(rule.src.as_ref())));
    parts.push(format!("to {}", target_or_any(rule.dst.as_ref())));
    if let Some(p) = rule.port {
        if p.from == p.to {
            parts.push(format!("port {}", p.from));
        } else {
            parts.push(format!("port {}:{}", p.from, p.to));
        }
    }
    if matches!(rule.action, Action::Allow | Action::Limit) {
        parts.push("flags S/SA keep state".into());
    }
    if matches!(rule.action, Action::Limit) {
        parts.push(
            "(max-src-conn 10, max-src-conn-rate 5/30, \
             overload <mufw_bruteforce> flush global)".into(),
        );
    }
    if let Some(c) = &rule.comment {
        parts.push(format!("# {c}"));
    }
    parts.join(" ")
}

fn target_or_any(t: Option<&Target>) -> String {
    match t {
        None | Some(Target::Any) => "any".into(),
        Some(Target::Host(ip)) => ip.to_string(),
        Some(Target::Cidr(net)) => net.to_string(),
    }
}

/// Build a header block for the mufw anchor.
pub fn anchor_header() -> String {
    [
        "# auto-generated by mufw — DO NOT EDIT BY HAND",
        "set block-policy drop",
        "set skip on lo0",
        "table <mufw_bruteforce> persist",
        "block in all",
        "pass out all keep state",
    ]
    .join("\n")
}

/// Render the entire anchor body from a rule slice.
pub fn render_anchor(rules: &[&Rule]) -> String {
    let mut out = anchor_header();
    out.push('\n');
    for r in rules {
        out.push_str(&to_anchor_line(r));
        out.push('\n');
    }
    out
}

/// Stub showing how a native `pfctl` filter rule would be constructed for
/// simple allow/deny cases. The CLI's apply path today uses the textual
/// anchor; this is retained for a future fast-path.
#[allow(dead_code)]
fn to_native_builder(rule: &Rule) -> Result<FilterRuleBuilder> {
    use pfctl::{FilterRuleAction, Direction};
    let mut b = FilterRuleBuilder::default();
    b.action(match rule.action {
        Action::Allow | Action::Limit => FilterRuleAction::Pass,
        Action::Deny => FilterRuleAction::Drop(pfctl::DropAction::Drop),
    });
    b.direction(Direction::In);
    b.proto(match rule.proto {
        Proto::Tcp => PfProto::Tcp,
        Proto::Udp => PfProto::Udp,
        Proto::Any => PfProto::Any,
    });
    Ok(b)
}
